### ISSUE TITLE
Problem to share playlist

### ISSUE THREAD

**Issue by nikolay-dementiev** [googledrive/drive-music-player#146]
I can not share the playlist access to selected users. I share the access to the playlist, as well as access to the folder on the disc also share the - but when you open under one of the Is the user for which you share the playlist - Playlist opens itself - but instead of writing all the tracks: _"You are not authorized to read this file or the file does not exist"_

**Comment by richardj** [comment]
Same problem here: 

Situation:

- create playlist with email address 1 in a folder that gives edit permissions to email 2 and email 3.
- email 2 tries to access playlist but gets `You are not authorized to read this file or the file does not exist` error message. 
- email 3 doesn't seem to have any problems with the same shared link.

In this case email 1 is the band's account, email 2 is my personal address, email 3 is that of another member of the band.

**Comment by nikolay-dementiev** [comment]
Many thanks. The problem is no longer relevant
