### ISSUE TITLE
http://www.driveplayer.com/ can't be found

### ISSUE THREAD

**Issue by yuval-harpaz** [googledrive/drive-music-player#213]
did the website fall? 
Dear team, I found the web app very useful, I can't use it since a few days ago

**Comment by nicolasgarnier** [comment]
Thanks so much for letting me know! Just changed registrar and it looks like the DNS configuration wasn't copied over.

It's now back online.

**Comment by yuval-harpaz** [comment]
great, thanks for the support, I enjoy this a lot
